# Generated by Django 5.2 on 2026-02-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("NEW", "New Lead (10%)"),
                            ("QUALIFIED", "Qualified (30%)"),
                            ("PROPOSAL", "Proposal Sent (60%)"),
                            ("NEGOTIATION", "Negotiation (80%)"),
                            ("WON", "Closed Won (100%)"),
                            ("LOST", "Closed Lost (0%)"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "probability",
                    models.PositiveIntegerField(default=10, editable=False),
                ),
            ],
        ),
    ]
